[project]
name = "FAF5-Analysis"
version = "0.1.0"
description = "Add a short description here"
authors = ["Danika MacDonell <danikam@mit.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tasks]

[dependencies]
django = ">=5.0.7,<6"
django-environ = ">=0.11.2,<0.12"
django-storages = ">=1.14.3,<2"
s3transfer = ">=0.10.2,<0.11"
boto3 = ">=1.34.150,<2"
botocore = ">=1.34.150,<2"
pandas = ">=2.2.2,<3"
geopandas = ">=1.0.1,<2"
geopy = ">=2.4.1,<3"
tqdm = ">=4.66.4,<5"
openpyxl = ">=3.1.4,<4"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.14.0,<2"
xlrd = ">=2.0.1,<3"
